on:
  release:
    types: [published]

name: Post Release

jobs:
  build:
    name: Post Release
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v1 # currently only v1 supports submodules
        with:
          submodules: recursive
          # fetch-depth: 0
      - name: generate binaries
        run: echo "here's where I would generate tars / zips of the full item"
      - name: attach binaries
        run: echo "here's where I would attach binaries to the release"